name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Canvia a la versió de Python que necessitis
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instal·la les dependències
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint main.py transform.py test.py  # Comprova els fitxers Python
    - name: Run tests
      run: |
        python -m unittest discover  # Executa els tests
    - name: Run coverage
      run: |
        pip install coverage
        coverage run -m unittest discover  # Executa els tests amb cobertura
        coverage report  # Mostra el report de cobertura
