yaml
image: python:3.8

stages:
  - test

before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pylint main.py 
    - python -m unittest discover  # Esto ejecutará tus pruebas
